apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "wanderlust.labels" . | nindent 4 }}
data:
  {{- range $key, $val := .Values.backend.env }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
