apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "wanderlust.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $val := .Values.secrets }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
