apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "wanderlust.labels" . | nindent 4 }}
    app: mongo
spec:
  serviceName: mongo-service
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        {{- include "wanderlust.labels" . | nindent 8 }}
        app: mongo
    spec:
      containers:
        - name: mongo
          image: {{ .Values.mongodb.image }}
          ports:
            - containerPort: {{ .Values.mongodb.port }}
          volumeMounts:
            - name: mongo-storage
              mountPath: /data/db
          resources:
            {{- toYaml .Values.mongodb.resources | nindent 12 }}
  volumeClaimTemplates:
    - metadata:
        name: mongo-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: {{ .Values.global.storageClass }}
        resources:
          requests:
            storage: {{ .Values.mongodb.storage }}
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-service
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "wanderlust.labels" . | nindent 4 }}
    app: mongo
spec:
  clusterIP: None
  selector:
    app: mongo
  ports:
    - port: {{ .Values.mongodb.port }}
      targetPort: {{ .Values.mongodb.port }}
      protocol: TCP
